### ISSUE TITLE
Prevent "Refund Upgrades" button in MvM from removing custom attributes until respawn

### ISSUE THREAD

**Issue by SoulBlast35** [nosoop/SM-TFCustomWeaponsX#15]
Self-explanatory. Custom Weapons 3 does this natively, and its just a little improvement I thought of

**Comment by nosoop** [comment]
The issue appears to happen because the game wipes runtime attributes matching the name of the upgrade; any attribute that isn't an upgrade is preserved.

The easiest fix for a server operator would be to use one of the alternate attribute names with the same class (if any exists) for that attribute in the CWX item config so it doesn't get wiped in the first place.  Bonus benefit of not displaying the upgrade as purchased in that case.

I don't do much modding for MvM; any idea if there are undesirable side effects that could happen if the player was regranted the item when respeccing?

**Comment by SoulBlast35** [comment]
I generally do try to use non-conflicting upgrades, I think it might be due to how CWX handles Weapon Permanence whereas CW3 refreshed the weapon if you did anything that updated it. Basically, every single time you bought an upgrade on a weapon, CW3 would regrant the weapon but it would have the bought upgrade. Dont quote me on this, but I think the reason why it worked is because when you clicked "Refund Upgrades", the game refunds them and respawns you. My theory is CW3 took this opportunity upon respawn to regrant the weapon to you, thereby placing the correct attributes back on the weapon. But for some reason, CWX doesnt do this. Is it possible to create a special case to regrant currently equipped weapons upon clicking "Refund Upgrades"?

As for side effects, the only one I had is that manually removing upgrades with the "-" buttons did not work at all. The point would be removed and the money count on the upgrade menu itself would update, but the "ching" sound did not play and the actual HUD money counter did not increase, and exiting the Upgrade menu basically just caused the upgrade points to come back.

**Comment by nosoop** [comment]
CW3 always refreshes the weapon once the game has (re)spawned weapons as necessary based on ownership / inventory, yes.  The game happens to reapply upgrades at some point after CW3 inserts its own weapons, though I'm not sure at which point.

>Is it possible to create a special case to regrant currently equipped weapons upon clicking "Refund Upgrades"?

That's the plan; it looks like the least invasive approach.

**Comment by nosoop** [comment]
Just pushed out the change for it; please give it a test and let me know if that resolves the issue.

**Comment by SoulBlast35** [comment]
Works fine from what I can tell. The only noticeable thing is that theres a very slight freeze after you hit the Refund button just before the plugin respawns you with your weapon. Other than that, works great.
